worker:
  name: myCookieTest
  maxTaskThreadNum: 100
  accessControlAllowOrigin: '*'
  security: {hasLoginCheck: false, hasAuth: false}
  admin:
    host: 127.0.0.1
    port: 9307
    nodeType: JOB_TRACKER
    registry: multicast
    registryAddress: 192.168.10.2:2181
    remotingNetworkManager: netty
    remotingServiceClient: tcp
    group: {name: cloudcareWorkerGroup, instance: worker}
  server: {host: 0.0.0.0, port: 8304, webContext: 'webapp'}

database:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull
  username: root
  password: "123456"
  maxIdle: 5
  maxActive: 100

oss: {
     alibaba: {apiKey: 8Ut9Q8SAt04TocIa, secretKey: rOMr9anzjY6VPBvdJuAUEGeVJ7bnCw, bucketName: test-qianxun, domain: hangzhou},
     ossObject: ossObject,
     originalFileName: originalFileName
     }

redis:
  server:
    ip: kvstore.cloudcare.com

